import google.generativeai as genai
from google.generativeai.types import HarmCategory, HarmBlockThreshold
import logging
import json
import re
from typing import Optional, Dict, List, Any

logger = logging.getLogger(__name__)

class GeminiClient:
    def __init__(self, api_key: str, model_name: str = "gemini-2.0-flash-exp"):
        """
        Initialize Gemini client
        
        Args:
            api_key: Google Gemini API key
            model_name: Model to use (default: gemini-2.0-flash-exp)
        """
        if not api_key:
            raise ValueError("Gemini API key is required")
        
        self.api_key = api_key
        self.model_name = model_name
        
        # Configure the API
        genai.configure(api_key=api_key)
        
        # Initialize the model with safety settings
        self.model = genai.GenerativeModel(
            model_name=model_name,
            safety_settings={
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
                HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
                HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
            }
        )
    
    def test_connection(self) -> dict:
        """Test API connection and return status"""
        try:
            # Simple test generation
            response = self.model.generate_content("Hello")
            return {
                "connected": True,
                "model": self.model_name,
                "error": None
            }
        except Exception as e:
            logger.error(f"Gemini connection test failed: {e}")
            return {
                "connected": False,
                "model": self.model_name,
                "error": str(e)
            }
    
    def generate_summary(self, transcript: str, system_prompt: str) -> str:
        """
        Generate session summary using Gemini
        
        Args:
            transcript: The session transcript
            system_prompt: System prompt for summarization
            
        Returns:
            Generated summary
        """
        try:
            # Prepare the full prompt
            full_prompt = f"""System Instructions: {system_prompt}

Please analyze the following TTRPG session transcript and generate a summary according to the instructions above.

Transcript:
{transcript}

Summary:"""

            # Generate content
            response = self.model.generate_content(
                full_prompt,
                generation_config=genai.types.GenerationConfig(
                    temperature=0.7,
                    top_p=0.9,
                    top_k=40,
                    max_output_tokens=2048,
                )
            )
            
            if response.candidates:
                return response.text.strip()
            else:
                raise Exception("No response generated by Gemini")
                
        except Exception as e:
            logger.error(f"Error generating summary with Gemini: {e}")
            raise Exception(f"Failed to generate summary: {str(e)}")

    def generate_summary_with_metadata(self, transcript: str, system_prompt: str) -> Dict[str, Any]:
        """
        Generate session summary and metadata suggestions in single optimized call
        
        Args:
            transcript: The session transcript
            system_prompt: System prompt for summarization
            
        Returns:
            Dictionary containing summary and metadata suggestions
        """
        # Create a highly structured prompt that enforces the exact format
        enhanced_prompt = f"""{system_prompt}

CRITICAL: Follow this EXACT format structure:

**Summary of Events:**
- [Major plot development or revelation]
- [Key combat outcome or story change]
- [Important discovery or event]

**Key Decisions & Next Steps:**
- [A choice the party made]
- [A goal or action item for the next session]
- [Unresolved situation requiring future action]

---METADATA---
{{
    "suggested_tags": [],
    "mentioned_characters": [],
    "mentioned_locations": [],
    "session_tone": [],
    "key_events": []
}}

INSTRUCTIONS:
1. First write the summary using the EXACT format above with "**Summary of Events:**" and "**Key Decisions & Next Steps:**"
2. Then add "---METADATA---" as a separator
3. Then add the JSON metadata block
4. Do NOT deviate from this structure

Metadata guidelines:
- suggested_tags: Activity types (combat, social, exploration, investigation, puzzle, travel) and tone (dramatic, comedic, tense, mystery, political)
- mentioned_characters: Names of NPCs, characters, or entities mentioned multiple times
- mentioned_locations: Place names mentioned in the session
- session_tone: Overall mood/tone descriptors
- key_events: Major story beats or important occurrences

Transcript:
{transcript}"""

        try:
            response = self.model.generate_content(
                enhanced_prompt,
                generation_config=genai.types.GenerationConfig(
                    temperature=0.3,  # Lower temperature for consistent formatting
                    top_p=0.9,
                    top_k=40,
                    max_output_tokens=2048,
                )
            )
            
            if response.candidates:
                full_response = response.text.strip()
                
                # Parse using the explicit separator
                metadata, summary = self._parse_with_separator(full_response)
                
                return {
                    "summary": summary,
                    "metadata": metadata
                }
            else:
                raise Exception("No response generated by Gemini")
                
        except Exception as e:
            logger.error(f"Error generating summary with metadata using Gemini: {e}")
            raise Exception(f"Failed to generate summary with metadata: {str(e)}")

    def _parse_with_separator(self, full_response: str) -> tuple[Dict[str, List[str]], str]:
        """Parse response using the explicit ---METADATA--- separator"""
        
        # First try the explicit separator
        if "---METADATA---" in full_response:
            parts = full_response.split("---METADATA---")
            summary = parts[0].strip()
            metadata_text = parts[1].strip()
            
            metadata = self._extract_json_from_text(metadata_text)
            if metadata:
                return metadata, summary
        
        # Fall back to the existing parsing strategies
        return self._parse_summary_and_metadata(full_response)

    def _generate_formatted_summary(self, transcript: str, system_prompt: str) -> str:
        """Generate summary with strict adherence to the format template"""
        
        # Create a very explicit prompt focused ONLY on the summary format
        summary_prompt = f"""{system_prompt}

CRITICAL FORMATTING REQUIREMENTS:
- You MUST use exactly this structure
- Start with "**Summary of Events:**" 
- Use bullet points starting with "- "
- Then "**Key Decisions & Next Steps:**"
- Use bullet points starting with "- "
- Do NOT add any other text, explanations, or JSON
- Do NOT use numbered lists
- Do NOT add introduction or conclusion text

Example of EXACT format required:

**Summary of Events:**
- The party encountered hostile forces at the village outskirts
- Combat engagement resulted in enemy casualties and tactical advantage

**Key Decisions & Next Steps:**
- Party chose to pursue retreating enemies rather than fortify position  
- Next session will focus on investigating the enemy camp for intelligence

Now analyze this transcript:

{transcript}"""

        try:
            response = self.model.generate_content(
                summary_prompt,
                generation_config=genai.types.GenerationConfig(
                    temperature=0.3,  # Lower temperature for more consistent formatting
                    top_p=0.9,
                    top_k=40,
                    max_output_tokens=1024,  # Shorter for focused summary
                )
            )
            
            if response.candidates:
                return response.text.strip()
            else:
                raise Exception("No response generated by Gemini")
                
        except Exception as e:
            logger.error(f"Error generating summary with Gemini: {e}")
            raise Exception(f"Failed to generate summary: {str(e)}")

    def _analyze_metadata_separately(self, transcript: str) -> Dict[str, List[str]]:
        """Analyze transcript separately for metadata extraction"""
        
        metadata_prompt = f"""Analyze this TTRPG transcript and extract metadata. Return ONLY valid JSON with this exact structure:

{{
    "suggested_tags": [],
    "mentioned_characters": [],
    "mentioned_locations": [],
    "session_tone": [],
    "key_events": []
}}

Guidelines:
- suggested_tags: Activity types (combat, social, exploration, investigation, puzzle, travel) and tone (dramatic, comedic, tense, mystery, political)
- mentioned_characters: Names of NPCs, characters, or entities mentioned multiple times
- mentioned_locations: Place names mentioned in the session
- session_tone: Overall mood/tone descriptors
- key_events: Major story beats or important occurrences

Only include clearly mentioned and significant items. Limit each array to 5-8 items.

Transcript:
{transcript}"""

        try:
            response = self.model.generate_content(
                metadata_prompt,
                generation_config=genai.types.GenerationConfig(
                    temperature=0.2,
                    top_p=0.9,
                    top_k=40,
                    max_output_tokens=512,
                )
            )
            
            if response.candidates:
                response_text = response.text.strip()
                
                # Parse JSON from response
                metadata = self._extract_json_from_text(response_text)
                if metadata:
                    return metadata
                else:
                    logger.warning("Could not parse metadata from Gemini response")
                    return self._empty_metadata()
            else:
                raise Exception("No response generated by Gemini")
                
        except Exception as e:
            logger.error(f"Error analyzing metadata with Gemini: {e}")
            return self._empty_metadata()

    def _empty_metadata(self) -> Dict[str, List[str]]:
        """Return empty metadata structure"""
        return {
            "suggested_tags": [],
            "mentioned_characters": [],
            "mentioned_locations": [],
            "session_tone": [],
            "key_events": []
        }

    def _generate_with_structured_output(self, transcript: str, system_prompt: str) -> Dict[str, Any]:
        """Generate using Gemini's structured output with JSON schema"""
        
        # Define the JSON schema for the response
        response_schema = {
            "type": "object",
            "properties": {
                "summary": {
                    "type": "string",
                    "description": "The session summary following the provided format"
                },
                "metadata": {
                    "type": "object",
                    "properties": {
                        "suggested_tags": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "Activity types and tone tags"
                        },
                        "mentioned_characters": {
                            "type": "array", 
                            "items": {"type": "string"},
                            "description": "Names of NPCs and characters mentioned"
                        },
                        "mentioned_locations": {
                            "type": "array",
                            "items": {"type": "string"}, 
                            "description": "Place names mentioned in the session"
                        },
                        "session_tone": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "Overall mood/tone descriptors"
                        },
                        "key_events": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "Major story beats or important occurrences"
                        }
                    },
                    "required": ["suggested_tags", "mentioned_characters", "mentioned_locations", "session_tone", "key_events"]
                }
            },
            "required": ["summary", "metadata"]
        }
        
        prompt = f"""System Instructions: {system_prompt}

Please analyze the following TTRPG session transcript and generate both a summary and metadata.

CRITICAL: The summary MUST follow this exact format:

**Summary of Events:**
- [Major plot development or revelation]
- [Key combat outcome or story change]
- [Important discovery or event]

**Key Decisions & Next Steps:**
- [A choice the party made]
- [A goal or action item for the next session]
- [Unresolved situation requiring future action]

For the metadata, also extract:
- suggested_tags: Activity types (combat, social, exploration, investigation, puzzle, travel) and tone (dramatic, comedic, tense, mystery, political)
- mentioned_characters: Names of NPCs, characters, or entities mentioned multiple times
- mentioned_locations: Place names mentioned in the session
- session_tone: Overall mood/tone descriptors
- key_events: Major story beats or important occurrences

Only include items that are clearly mentioned and significant. Limit each array to 5-8 most relevant items.

Transcript:
{transcript}"""

        # Generate content with structured output
        response = self.model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.7,
                top_p=0.9,
                top_k=40,
                max_output_tokens=3072,
                response_mime_type="application/json",
                response_schema=response_schema
            )
        )
        
        if response.candidates:
            # Parse the structured JSON response
            result = json.loads(response.text)
            return {
                "summary": result["summary"],
                "metadata": result["metadata"]
            }
        else:
            raise Exception("No response generated by Gemini")

    def _generate_with_text_parsing(self, transcript: str, system_prompt: str) -> Dict[str, Any]:
        """Generate using text parsing approach (fallback)"""
        
        full_prompt = f"""System Instructions: {system_prompt}

Please analyze the following TTRPG session transcript and:
1. Generate a summary according to the instructions above
2. Provide metadata suggestions in JSON format

CRITICAL: The summary MUST follow this exact format:

**Summary of Events:**
- [Major plot development or revelation]
- [Key combat outcome or story change]
- [Important discovery or event]

**Key Decisions & Next Steps:**
- [A choice the party made]
- [A goal or action item for the next session]
- [Unresolved situation requiring future action]

After the summary, add this JSON metadata block:

METADATA_JSON:
{{
    "suggested_tags": [],
    "mentioned_characters": [],
    "mentioned_locations": [],
    "session_tone": [],
    "key_events": []
}}

Guidelines for metadata:
- suggested_tags: Activity types (combat, social, exploration, investigation, puzzle, travel) and tone (dramatic, comedic, tense, mystery, political)
- mentioned_characters: Names of NPCs, characters, or entities mentioned multiple times
- mentioned_locations: Place names mentioned in the session
- session_tone: Overall mood/tone descriptors
- key_events: Major story beats or important occurrences

Only include items that are clearly mentioned and significant. Limit each array to 5-8 most relevant items.

Transcript:
{transcript}"""

        # Generate content
        response = self.model.generate_content(
            full_prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.7,
                top_p=0.9,
                top_k=40,
                max_output_tokens=3072,
            )
        )
        
        if response.candidates:
            full_response = response.text.strip()
            
            # Extract metadata from response using multiple parsing strategies
            metadata, summary = self._parse_summary_and_metadata(full_response)
            
            return {
                "summary": summary,
                "metadata": metadata
            }
        else:
            raise Exception("No response generated by Gemini")

    def _parse_summary_and_metadata(self, full_response: str) -> tuple[Dict[str, List[str]], str]:
        """
        Parse summary and metadata from LLM response using multiple strategies
        
        Args:
            full_response: The full response from the LLM
            
        Returns:
            Tuple of (metadata, summary)
        """
        empty_metadata = {
            "suggested_tags": [],
            "mentioned_characters": [],
            "mentioned_locations": [],
            "session_tone": [],
            "key_events": []
        }
        
        # Strategy 1: Look for METADATA_JSON: delimiter
        if "METADATA_JSON:" in full_response:
            parts = full_response.split("METADATA_JSON:")
            summary = parts[0].strip()
            metadata_text = parts[1].strip()
            
            metadata = self._extract_json_from_text(metadata_text)
            if metadata:
                return metadata, summary
        
        # Strategy 2: Look for ```json code blocks
        json_block_pattern = r'```json\s*\n(.*?)\n```'
        matches = re.findall(json_block_pattern, full_response, re.DOTALL)
        if matches:
            # Take the last JSON block (most likely to be metadata)
            metadata_text = matches[-1].strip()
            metadata = self._extract_json_from_text(metadata_text)
            if metadata:
                # Remove the JSON block from summary
                summary = re.sub(json_block_pattern, '', full_response, flags=re.DOTALL).strip()
                # Clean up any "**Metadata JSON:**" headers
                summary = re.sub(r'\*\*Metadata JSON:\*\*\s*', '', summary).strip()
                return metadata, summary
        
        # Strategy 3: Look for any JSON object in the response
        json_pattern = r'\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}'
        json_matches = re.findall(json_pattern, full_response, re.DOTALL)
        for json_text in reversed(json_matches):  # Check from end, more likely to be metadata
            metadata = self._extract_json_from_text(json_text)
            if metadata and any(metadata.values()):  # Check if metadata has actual content
                # Remove the JSON from summary
                summary = full_response.replace(json_text, '').strip()
                # Clean up any headers
                summary = re.sub(r'\*\*Metadata JSON:\*\*\s*', '', summary).strip()
                return metadata, summary
        
        # No metadata found, return empty metadata and full response as summary
        logger.warning("Could not extract metadata from Gemini response, using empty metadata")
        return empty_metadata, full_response

    def _extract_json_from_text(self, text: str) -> Optional[Dict[str, List[str]]]:
        """
        Extract and parse JSON from text, handling various formats
        
        Args:
            text: Text that should contain JSON
            
        Returns:
            Parsed metadata dictionary or None if parsing fails
        """
        try:
            # Clean up the text
            text = text.strip()
            
            # Remove markdown formatting
            text = text.replace('```json', '').replace('```', '').strip()
            
            # If text doesn't start with {, try to find JSON object
            if not text.startswith('{'):
                json_start = text.find('{')
                if json_start != -1:
                    text = text[json_start:]
            
            # If text doesn't end with }, try to find end of JSON object
            if not text.endswith('}'):
                json_end = text.rfind('}')
                if json_end != -1:
                    text = text[:json_end + 1]
            
            # Parse JSON
            metadata = json.loads(text)
            
            # Validate that it has the expected structure
            expected_keys = {"suggested_tags", "mentioned_characters", "mentioned_locations", "session_tone", "key_events"}
            if isinstance(metadata, dict) and any(key in metadata for key in expected_keys):
                # Ensure all expected keys exist with empty lists as defaults
                for key in expected_keys:
                    if key not in metadata:
                        metadata[key] = []
                    elif not isinstance(metadata[key], list):
                        metadata[key] = []
                
                return metadata
            
        except (json.JSONDecodeError, ValueError, TypeError) as e:
            logger.debug(f"Failed to parse JSON from text: {e}")
        
        return None
    
    def estimate_tokens(self, text: str) -> int:
        """
        Estimate token count for input text
        
        Args:
            text: Input text to estimate
            
        Returns:
            Estimated token count
        """
        try:
            result = self.model.count_tokens(text)
            return result.total_tokens
        except Exception as e:
            logger.warning(f"Could not count tokens: {e}")
            # Rough estimation: ~4 characters per token
            return len(text) // 4
    
    def check_content_length(self, transcript: str, system_prompt: str) -> dict:
        """
        Check if content fits within model limits
        
        Args:
            transcript: The session transcript
            system_prompt: System prompt
            
        Returns:
            Dict with length info and recommendations
        """
        full_content = f"{system_prompt}\n\nTranscript:\n{transcript}"
        estimated_tokens = self.estimate_tokens(full_content)
        
        # Gemini 2.0 Flash has ~1M token context window
        max_tokens = 1000000
        max_recommended = int(max_tokens * 0.8)  # Leave room for output
        
        return {
            "estimated_tokens": estimated_tokens,
            "max_tokens": max_tokens,
            "within_limit": estimated_tokens < max_recommended,
            "usage_percent": (estimated_tokens / max_tokens) * 100,
            "recommendation": (
                "Content fits within limits" if estimated_tokens < max_recommended
                else "Content may be too long, consider splitting transcript"
            )
        }
    
    def analyze_metadata(self, transcript: str) -> Dict[str, List[str]]:
        """
        Analyze transcript and suggest metadata tags, characters, and locations
        
        Args:
            transcript: The session transcript
            
        Returns:
            Dictionary with suggested metadata
        """
        try:
            # Prepare the analysis prompt
            analysis_prompt = f"""Analyze the following TTRPG session transcript and extract metadata. Return ONLY a JSON object with the following structure:
{{
    "suggested_tags": [],
    "mentioned_characters": [],
    "mentioned_locations": [],
    "session_tone": [],
    "key_events": []
}}

Guidelines:
- suggested_tags: Activity types (combat, social, exploration, investigation, puzzle, travel) and tone (dramatic, comedic, tense, mystery, political)
- mentioned_characters: Names of NPCs, characters, or entities mentioned multiple times
- mentioned_locations: Place names mentioned in the session
- session_tone: Overall mood/tone descriptors
- key_events: Major story beats or important occurrences

Only include items that are clearly mentioned and significant. Limit each array to 5-8 most relevant items.

Transcript:
{transcript}

JSON Response:"""

            # Generate content
            response = self.model.generate_content(
                analysis_prompt,
                generation_config=genai.types.GenerationConfig(
                    temperature=0.3,
                    top_p=0.9,
                    top_k=40,
                    max_output_tokens=1024,
                )
            )
            
            if response.candidates:
                result_text = response.text.strip()
                # Try to extract JSON from the response
                if result_text.startswith('{') and result_text.endswith('}'):
                    try:
                        return json.loads(result_text)
                    except json.JSONDecodeError:
                        pass
                
                # Fallback: try to find JSON in the response
                json_start = result_text.find('{')
                json_end = result_text.rfind('}') + 1
                if json_start != -1 and json_end > json_start:
                    try:
                        json_content = result_text[json_start:json_end]
                        return json.loads(json_content)
                    except json.JSONDecodeError:
                        pass
                
                # If JSON parsing fails, return empty structure
                logger.warning("Could not parse JSON from Gemini metadata analysis response")
                return {
                    "suggested_tags": [],
                    "mentioned_characters": [],
                    "mentioned_locations": [],
                    "session_tone": [],
                    "key_events": []
                }
            else:
                raise Exception("No response generated by Gemini")
                
        except Exception as e:
            logger.error(f"Error analyzing metadata with Gemini: {e}")
            return {
                "suggested_tags": [],
                "mentioned_characters": [],
                "mentioned_locations": [],
                "session_tone": [],
                "key_events": []
            }