"""
Google Gemini LLM client for cloud-based model inference.

Handles Gemini API configuration, safety settings, and API calls.
Inherits common parsing and prompt building from BaseLLMClient.
"""

import google.generativeai as genai
from google.generativeai.types import HarmCategory, HarmBlockThreshold
import logging

from llm.base import BaseLLMClient
from prompts import build_simple_prompt

logger = logging.getLogger(__name__)


class GeminiClient(BaseLLMClient):
    def __init__(self, api_key: str, model_name: str = "gemini-2.0-flash-exp"):
        """
        Initialize Gemini client

        Args:
            api_key: Google Gemini API key
            model_name: Model to use (default: gemini-2.0-flash-exp)
        """
        if not api_key:
            raise ValueError("Gemini API key is required")

        self.api_key = api_key
        self.model_name = model_name

        # Configure the API
        genai.configure(api_key=api_key)

        # Initialize the model with safety settings
        self.model = genai.GenerativeModel(
            model_name=model_name,
            safety_settings={
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
                HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
                HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
            }
        )

    def _call_llm(self, prompt: str, **kwargs) -> str:
        """
        Call Gemini API and return the response text.

        Args:
            prompt: The full prompt to send
            **kwargs: Additional parameters (temperature, max_tokens, etc.)

        Returns:
            Raw response text from Gemini
        """
        # Extract optional parameters
        temperature = kwargs.get('temperature', 0.7)
        max_tokens = kwargs.get('max_tokens', 2048)

        try:
            response = self.model.generate_content(
                prompt,
                generation_config=genai.types.GenerationConfig(
                    temperature=temperature,
                    top_p=0.9,
                    top_k=40,
                    max_output_tokens=max_tokens,
                )
            )

            if response.candidates:
                return response.text.strip()
            else:
                raise Exception("No response generated by Gemini")

        except Exception as e:
            logger.error(f"Error calling Gemini API: {e}")
            raise Exception(f"Failed to generate response: {str(e)}")

    def generate_summary(self, transcript: str, system_prompt: str) -> str:
        """
        Generate session summary using Gemini (without metadata extraction).

        Args:
            transcript: The session transcript
            system_prompt: System prompt for summarization

        Returns:
            Generated summary
        """
        # Build simple prompt without metadata instructions
        full_prompt = f"""System Instructions: {system_prompt}

Please analyze the following TTRPG session transcript and generate a summary according to the instructions above.

Transcript:
{transcript}

Summary:"""

        return self._call_llm(full_prompt, temperature=0.7, max_tokens=2048)

    def test_connection(self) -> dict:
        """Test API connection and return status"""
        try:
            # Simple test generation
            response = self.model.generate_content("Hello")
            return {
                "connected": True,
                "model": self.model_name,
                "error": None
            }
        except Exception as e:
            logger.error(f"Gemini connection test failed: {e}")
            return {
                "connected": False,
                "model": self.model_name,
                "error": str(e)
            }

    def estimate_tokens(self, text: str) -> int:
        """
        Estimate token count for input text

        Args:
            text: Input text to estimate

        Returns:
            Estimated token count
        """
        try:
            result = self.model.count_tokens(text)
            return result.total_tokens
        except Exception as e:
            logger.warning(f"Could not count tokens: {e}")
            # Rough estimation: ~4 characters per token
            return len(text) // 4

    def check_content_length(self, transcript: str, system_prompt: str) -> dict:
        """
        Check if content fits within model limits

        Args:
            transcript: The session transcript
            system_prompt: System prompt

        Returns:
            Dict with length info and recommendations
        """
        full_content = f"{system_prompt}\n\nTranscript:\n{transcript}"
        estimated_tokens = self.estimate_tokens(full_content)

        # Gemini 2.0 Flash has ~1M token context window
        max_tokens = 1000000
        max_recommended = int(max_tokens * 0.8)  # Leave room for output

        return {
            "estimated_tokens": estimated_tokens,
            "max_tokens": max_tokens,
            "within_limit": estimated_tokens < max_recommended,
            "usage_percent": (estimated_tokens / max_tokens) * 100,
            "recommendation": (
                "Content fits within limits" if estimated_tokens < max_recommended
                else "Content may be too long, consider splitting transcript"
            )
        }
